// pw-front-svelte/src/components/players/playerItem.svelte
<script>
	import { goto } from '$app/navigation';

	/**
	 * @type {{ value: string; stats: { stat: { birthtimeMs: string | number | Date; }; }; }}
	 */
	export let player;
</script>

<div class="card p-4" style="width: 300px">
	<div class="flex flex-col gap-4">
		<div class="flex justify-between">
			<div>Player ID:</div>
			<div class="text-wrap break-all" style="max-width: 50%">{player?.value}</div>
		</div>

		<div class="flex justify-between">
			<div>Erstellt am:</div>
			<div>{new Date(player?.stats?.stat?.birthtimeMs).toLocaleString('de-DE')}</div>
		</div>

		<button
			type="button"
			class="btn variant-filled-primary"
			on:click={() => goto('/players/' + player?.value?.slice(0, -4))}>Anzeigen</button
		>
	</div>
</div>

// pw-front/src/components/playerItem.vue
<template>
  <div>
    <q-card>
      <q-card-section>
        <div class="row wrap q-col-gutter-md">
          <div class="col-auto wrap">
            <div>Player ID: </div>
            <div>Erstellt am: </div>
          </div>

          <div class="col wrap">
            <div>{{ player?.value }}</div>
            <div>{{ new Date(player?.stats?.stat?.birthtimeMs).toLocaleString('de-DE') }}</div>
          </div>
        </div>
      </q-card-section>
      <q-card-section>
        <q-btn color="primary" :to="`/paldex/${player?.value?.slice(0, -4)}`">Anzeigen</q-btn>
      </q-card-section>
    </q-card>
  </div>
</template>

<script lang="ts">
import { defineComponent} from 'vue';

export default defineComponent({
  name: 'playerItem',
  components: {  },
  props: {
    player: Object,
  },
  setup () {
    return {  };
  }
});
</script>
